### ISSUE TITLE
Selecting Quit from main.py

### ISSUE THREAD

**Issue by beaesguerra** [enochtsang/TerminalFighter#42] opened 2015-12-23 21:27 UTC
Game closes properly, but I get this error: 

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    gamestate = run_game_state.get(gamestate, sys.exit)(screen, DRAWING_SCALE)
TypeError: exit expected at most 1 arguments, got 2

**Comment by ExtraGravity** [comment] 2015-12-23 21:37
Yea, I saw that. Not sure how to fix it, it's a fairly non issue thing right now though.

**Comment by bseto** [comment] 2015-12-23 21:41
This is a result of not properly closing pygame. 

Example: In SDL2, I have to call:

```
void close()
{
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    window = NULL;
    renderer = NULL;
    SDL_Quit();
    exit(0);
}
```

Try to call https://www.pygame.org/docs/ref/pygame.html#pygame.quit before exit?

**Comment by ExtraGravity** [comment] 2015-12-23 21:46
No, the problem is in the dict I use for moving between game states. Game states are a function that takes 2 arguments. `sys.exit()` takes either 0 or 1 argument.

**Comment by bseto** [comment] 2015-12-23 22:15
ohh i see

**Comment by ExtraGravity** [comment] 2015-12-23 22:17
Not sure if you guys want to do something about that

**Comment by bseto** [comment] 2015-12-24 04:58
Nah, I think if you don't think its worth the effort its okay

**Comment by ExtraGravity** [comment] 2016-01-04 08:26
I fixed the previous issues.

**Closed as completed by ExtraGravity** 2016-01-04 08:26 UTC
